FROM nginx:alpine

# Copia toda a estrutura de arquivos da pasta frontend para o diretório de arquivos do Nginx
COPY . /usr/share/nginx/html

# Expõe a porta 80 para acessar o servidor Nginx
EXPOSE 80
