services:
  frontend:
    build: ./frontend
    container_name: fullstack_frontend
    volumes: 
      - ./frontend:/html
    depends_on:
      - backend
    ports:
      - "8001:80"
      
  backend:
    build: ./backend
    container_name: fullstack_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_KEY=base64:jn3FymuNYWgkoEaiGhh3F58Sz9V9lyWQTWRXpanSpoY=
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=test_docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - JWT_SECRET=ptAPWDPTgPbnByUt7CKtV8fAQaaww0uVPft4bwEWzXvb8R9UKWWUz0zeQhLNc6vj

  db:
    image: mysql:8
    container_name: fullstack_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_docker
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fullstack_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: